__title__ = "JDBC intercom handler"
__package_name__ = "mindsdb_jdbc_handler"
__version__ = '0.0.1'
__description__ = 'Generic JDBC handler for MindsDB, allowing connection to any database with a valid JDBC driver.'
__author__ = "gemini"
__github__ = "https://github.com/mindsdb/mindsdb"
__pypi__ = "https://pypi.org/project/mindsdb/"
__license__ = "MIT"
__copyright__ = "Copyright 2025 - mindsdb"